name: Android CI

on:
  push:
    branches:
      - master
      - test/**
  pull_request:
    types: [opened, synchronize, reopened]

env:
  ANDROID_API: 36.1
  ANDROID_BUILD_TOOLS: 36.1.0
  ADB_INSTALL_TIMEOUT: 5

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install necessary tools
        run: |
          sudo apt install -y zipalign apksigner

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Restore cache for Git LFS Objects
        id: lfs-cache
        uses: actions/cache@v4
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.git/lfs/objects/**') }}
          restore-keys: ${{ runner.os }}-lfs-

      - name: Git LFS Pull
        run: git lfs pull

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager "tools"
          sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"
          sdkmanager "platforms;android-${ANDROID_API}"
          sdkmanager "extras;android;m2repository"
          sdkmanager "extras;google;m2repository"
          sdkmanager "extras;google;google_play_services"
          
      - name: Prepare builddir
        run: |
          echo "mapboxAccessToken=${{ secrets.MAPBOX_PK }}" > $GITHUB_WORKSPACE/mapbox.properties
          echo "mapboxDownloadToken=${{ secrets.MAPBOX_SK }}" >> $GITHUB_WORKSPACE/mapbox.properties
          chmod +x gradlew

      - name: Build APKs
        run: ./gradlew app:assembleRelease wear:assemble

      - name: Align and sign APKs
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS_PASS: ${{ secrets.KEYSTORE_ALIAS_PASS }}
        run: |
          # Write keystore
          echo "${{ secrets.KEYSTORE }}" | base64 -d > keystore.jks
          
          for apk in $(find */build/outputs -type f -name "*-release-unsigned.apk"); do
            project_name=$(basename ${apk} -release-unsigned.apk)
          
            # Align APK
            zipalign -v -f -p 4 "${apk}" "./${project_name}-unsigned-aligned.apk"
            
            # Sign APK
            apksigner sign --ks keystore.jks --ks-pass env:KEYSTORE_PASS --ks-key-alias '${{ secrets.KEYSTORE_ALIAS }}' --key-pass env:KEYSTORE_ALIAS_PASS --out "./${project_name}-release.apk" "./${project_name}-unsigned-aligned.apk"
          done

      - name: Upload generated APK
        uses: actions/upload-artifact@v4
        with:
          name: released-apks
          path:
            ./*-release.apk